config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dictionaries, shallow: true do
    resources :words
  end

  namespace :admin do
    resources :users, only: [:index]
    resources :levels, only: [:index, :create]
    resources :teachers
    resources :guests, only: [:index]
    post 'guest_to_group' => 'guests#guest_to_group'
    post 'join_to_level' => 'groups#join_to_level', :as => :join_to_level
    post 'join_to_group' => 'users#join_to_group', :as => :join_to_group
    resources :groups, only: [:index, :create]
    resources :dictionaries
    get '/' => 'admin#index', :as => :root
  end

  namespace :teacher do
    get '/' => 'teacher#index', :as => :root
    resources :dictionaries
    resources :groups, only: [:index]
  end

  resources :testing, only: [:index]

  get 'result' => 'result#index', :as => :index_result

  post 'testing/answer' => 'testing#answer', :as => :answer_testing

  post 'trainers/start' => 'trainers#start', :as => :start_trainers

  resources :trainers

  root 'trainers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :dictionary
  has_and_belongs_to_many :trainers
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show

  end

  # GET /words/new
  def new
    @dictionary = Dictionary.find(params[:dictionary_id])
    @word = @dictionary.words.build
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @dictionary = Dictionary.find(params[:dictionary_id])
    @word = @dictionary.words.build(word_params)
    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
        format.js
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:foreign_word, :translate, :dictionary_id)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_errorMessage.html.erb
<% @word.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <strong><%= message %></strong>
    </div>
<% end %>

app/views/words/_form.html.erb
<%= form_for([@dictionary, @dictionary.words.build],  remote: true) do |f| %>

    <div class="row">
      <div class="col-md-6">
        <div class="field form-group">
          <%= f.text_field :foreign_word, :type => "text", :class => "form-control" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="field form-group">
          <%= f.text_field :translate, :type => "text", :class => "form-control" %>
        </div>
      </div>
    </div>

  <div class="actions">
    <%= f.submit "Добвать слово", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/words/create.js.erb
<% if @word.errors.present? %>

$(".modal-body").append("<%= j render 'errorMessage', word: @word %>");

<% else %>
location.reload();
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Foreign word</th>
      <th>Translate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.foreign_word %></td>
        <td><%= word.translate %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/new.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Новое слово");

// Render the new form
$('.modal-body').html('<%= j render 'form', word: @word %> ');

// Show the dynamic dialog
$('#dialog').modal("show");

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foreign word:</strong>
  <%= @word.foreign_word %>
</p>

<p>
  <strong>Translate:</strong>
  <%= @word.translate %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>