config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :dictionaries, shallow: true do
    resources :words
  end

  namespace :admin do
    resources :users, only: [:index]
    resources :levels, only: [:index, :create]
    resources :teachers
    resources :guests, only: [:index]
    post 'guest_to_group' => 'guests#guest_to_group'
    post 'join_to_level' => 'groups#join_to_level', :as => :join_to_level
    post 'join_to_group' => 'users#join_to_group', :as => :join_to_group
    resources :groups, only: [:index, :create]
    resources :dictionaries
    get '/' => 'admin#index', :as => :root
  end

  namespace :teacher do
    get '/' => 'teacher#index', :as => :root
    resources :dictionaries
    resources :groups, only: [:index]
  end

  resources :testing, only: [:index]

  get 'result' => 'result#index', :as => :index_result

  post 'testing/answer' => 'testing#answer', :as => :answer_testing

  post 'trainers/start' => 'trainers#start', :as => :start_trainers

  resources :trainers

  root 'trainers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dictionary.rb
class Dictionary < ApplicationRecord
  has_many :words
  belongs_to :user
  has_and_belongs_to_many :trainers
  validates :dict_name, presence: true
end

app/controllers/admin/dictionaries_controller.rb
class Admin::DictionariesController < Admin::AdminController

  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index

  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
    @words = @dictionary.words
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)
    @dictionary.user = current_user

    respond_to do |format|

      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
        format.js
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dictionary
    @dictionary = Dictionary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dictionary_params
    params.require(:dictionary).permit(:dict_name, :user_id)
  end
end

app/controllers/dictionaries_controller.rb
class DictionariesController < ApplicationController

  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index
    @dictionaries = Dictionary.all
  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
    @words = @dictionary.words
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)
    @dictionary.user = current_user

    respond_to do |format|

      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
        format.js
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dictionary
    @dictionary = Dictionary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dictionary_params
    params.require(:dictionary).permit(:dict_name, :user_id)
  end
end

app/controllers/teacher/dictionaries_controller.rb
class Teacher::DictionariesController < Teacher::TeacherController

  before_action :set_dictionary, only: [:show, :edit, :update, :destroy]

  # GET /dictionaries
  # GET /dictionaries.json
  def index

  end

  # GET /dictionaries/1
  # GET /dictionaries/1.json
  def show
    @words = @dictionary.words
  end

  # GET /dictionaries/new
  def new
    @dictionary = Dictionary.new
  end

  # GET /dictionaries/1/edit
  def edit
  end

  # POST /dictionaries
  # POST /dictionaries.json
  def create
    @dictionary = Dictionary.new(dictionary_params)
    @dictionary.user = current_user

    respond_to do |format|

      if @dictionary.save
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully created.' }
        format.json { render :show, status: :created, location: @dictionary }
        format.js
      else
        format.html { render :new }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /dictionaries/1
  # PATCH/PUT /dictionaries/1.json
  def update
    respond_to do |format|
      if @dictionary.update(dictionary_params)
        format.html { redirect_to @dictionary, notice: 'Dictionary was successfully updated.' }
        format.json { render :show, status: :ok, location: @dictionary }
      else
        format.html { render :edit }
        format.json { render json: @dictionary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dictionaries/1
  # DELETE /dictionaries/1.json
  def destroy
    @dictionary.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Dictionary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dictionary
    @dictionary = Dictionary.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dictionary_params
    params.require(:dictionary).permit(:dict_name, :user_id)
  end
end

app/helpers/dictionaries_helper.rb
module DictionariesHelper
end

app/views/admin/dictionaries/_all.html.erb
<% @dictionaries.each do |dictionary| %>
    <li>
      <%= link_to dictionary.dict_name , dictionary %>
    </li>
<% end %>

app/views/admin/dictionaries/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/admin/dictionaries/_errorMessage.html.erb
<% @dictionary.errors.full_messages.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <strong><%= message %></strong>
    </div>
<% end %>

app/views/admin/dictionaries/_form.html.erb
<%= form_for(dictionary, remote: true) do |f| %>

    <div class="field form-group">
      <%= f.text_field :dict_name, :type => "text", :class => "form-control" %>
    </div>
    <div class="actions btn btn-default">
      <%= f.submit "Добвать словарь" %>
    </div>
<% end %>

app/views/admin/dictionaries/_successMessage.html.erb
<div class="product-options">
  <a  id="myWish" href="javascript:;"  class="btn btn-mini" >Add to Wishlist </a>
  <a  href="" class="btn btn-mini"> Purchase </a>
</div>
<div class="alert alert-success" id="success-alert">
  <strong>Success! </strong>
  Product have added to your wishlist.
</div>

app/views/admin/dictionaries/create.js.erb
<% if @dictionary.errors.present? %>

$(".modal-body").append("<%= j render 'errorMessage', dictionary: @dictionary %>");

<% else %>
location.reload();
<% end %>

app/views/admin/dictionaries/index.html.erb
<h1>Show Dicts</h1>

app/views/admin/dictionaries/new.js.erb
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Название словаря");

// Render the new form
$('.modal-body').html('<%= j render 'form', dictionary: @dictionary %> ');

// Show the dynamic dialog
$('#dialog').modal("show");

app/views/admin/dictionaries/show.html.erb
<div class="row">
  <div class="panel panel-default">
    <div class="panel-body text-center">
      <h4><%= @dictionary.dict_name %></h4>
    </div>
  </div>
  <table class="table table-striped table_words">
    <thead>
    <tr>
      <th>Слово <%= link_to(raw("<i class='fa fa-plus-circle fa-2x' aria-hidden='true'></i>"), new_dictionary_word_path(@dictionary), remote: true, 'data-toggle' => "modal", 'data-target' => "dialog") %></th>
      <th colspan="3">Перевод</th>

    </tr>
    </thead>
    <tbody>
    <% @words.each do |word| %>
        <tr>
          <td><%= word.foreign_word %></td>
          <td><%= word.translate %></td>
          <td class="text-right">
            <span><i class="fa fa-pencil fa-2x" aria-hidden="true"></i></span><span><i class="fa fa-trash fa-2x" aria-hidden="true"></i></span>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>